### ISSUE TITLE
CallbackProxy does not support boolean operations

### ISSUE THREAD

**Issue by miki725** [soulrebel/objproxies#2]
```python
>>> def foo(): return False
>>> any([False, CallbackProxy(foo)])
Traceback (most recent call last):
  File "<ipython-input-15-3cb141dff2a9>", line 1, in <module>
    any([False, CallbackProxy(foo)])
  File "<string>", line 1, in __len__
TypeError: object of type 'bool' has no len()
```

**Comment by soulrebel** [comment]
Works for me. What python version are you on?

**Comment by miki725** [comment]
``` bash
$ python --version
Python 2.7.3
```

I found the package on PyPI but didnt realize that Python2 was not supported as I just read in readme. I see that on latest Python 2 import fails:

``` python
>>> from objproxies import CallbackProxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/e003134/.virtualenvs/test/lib/python2.7/site-packages/objproxies.py", line 5, in <module>
    'objproxies requires Python 3. For Python 2, refer to ProxyTypes '
ImportError: objproxies requires Python 3. For Python 2, refer to ProxyTypes <http://cheeseshop.python.org/pypi/ProxyTypes>
```

Maybe add similar exception to older Python versions as well?

**Comment by neg3ntropy** [comment]
I don't feel one should touch old versions. 
Anyhow, now there is a "fix", so I am closing. Thanks.
